symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    lifetime: 3600          # a reset link is valid for 1 hour
    throttle_limit: 900     # a new link for the same account at most every 15 minutes
