<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261001151021 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE weight_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, weight_kg DOUBLE PRECISION NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1486C8C0A76ED395AA9E377A ON weight_entry (user_id, date)');
        $this->addSql('CREATE INDEX IDX_1486C8C0A76ED395 ON weight_entry (user_id)');
        $this->addSql('ALTER TABLE weight_entry ADD CONSTRAINT FK_1486C8C0A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE weight_entry DROP CONSTRAINT FK_1486C8C0A76ED395');
        $this->addSql('DROP TABLE weight_entry');
    }
}
