<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261001162718 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE exercise_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, raw_text TEXT NOT NULL, performed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, kcal DOUBLE PRECISION NOT NULL, status VARCHAR(20) DEFAULT \'estimated\' NOT NULL, estimated_by VARCHAR(100) DEFAULT NULL, estimation_attempts INT DEFAULT 0 NOT NULL, last_estimation_attempt_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_estimation_error TEXT DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E176AB2A76ED395CC77A1DC ON exercise_entry (user_id, performed_at)');
        $this->addSql('CREATE INDEX IDX_E176AB2A76ED395 ON exercise_entry (user_id)');
        $this->addSql('CREATE TABLE exercise_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, minutes DOUBLE PRECISION DEFAULT NULL, kcal DOUBLE PRECISION NOT NULL, assumption TEXT DEFAULT NULL, entry_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_463E47ACBA364942 ON exercise_item (entry_id)');
        $this->addSql('ALTER TABLE exercise_entry ADD CONSTRAINT FK_E176AB2A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exercise_item ADD CONSTRAINT FK_463E47ACBA364942 FOREIGN KEY (entry_id) REFERENCES exercise_entry (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exercise_entry DROP CONSTRAINT FK_E176AB2A76ED395');
        $this->addSql('ALTER TABLE exercise_item DROP CONSTRAINT FK_463E47ACBA364942');
        $this->addSql('DROP TABLE exercise_entry');
        $this->addSql('DROP TABLE exercise_item');
    }
}
